### PR TITLE
update env_logger to 0.11

### PR DESCRIPTION
**Pull request by yanns**
https://github.com/rust-cli/env_logger/blob/HEAD/CHANGELOG.md#0110---2024-01-19

### CODE REVIEW

**Comment by d-e-s-o** [comment]
Thanks

**Comment by yanns** [comment]
@d-e-s-o it'd be great to have a release with this, so that we can update `env_logger` in our applications.

**Comment by d-e-s-o** [comment]
> @d-e-s-o it'd be great to have a release with this, so that we can update `env_logger` in our applications.

I'd rather wait some more. The crate doesn't have a formal MSRV policy right now, but N-5 is the bare minimum from my point of view. I'd prefer N-6 or "higher". Why is it so important that this crate uses `env_logger` `0.11`?

**Comment by yanns** [comment]
I had this error when trying to update `env_logger`:

```
Command failed: cargo update --config net.git-fetch-with-cli=true --manifest-path Cargo.toml --package env_logger@0.10.2 --precise 0.11.1
    Updating crates.io index
error: failed to select a version for the requirement `env_logger = "^0.10"`
candidate versions found which didn't match: 0.11.1
location searched: crates.io index
required by package `test-log v0.2.14`
    ... which satisfies dependency `test-log = "^0.2"` (locked to 0.2.14) of package `reference_service v0.1.0 (/tmp/renovate/repos/github/commercetools/reference_service)`
perhaps a crate was updated and forgotten to be re-vendored?
```
It's not completely blocking as I can still update the dependency though.

**Pull request merged**
